name: Fellowship Weekly Automation

on:
  schedule:
    - cron: '0 6 * * 0'
    - cron: '0 6 * * 1'
  workflow_dispatch:
    inputs:
      day_to_test:
        description: 'Which script do you want to manually test?'
        required: true
        default: 'Sunday'
        type: choice
        options:
          - Sunday
          - Monday

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas gspread oauth2client pytz

      - name: Run Sunday Script
        if: github.event.schedule == '0 6 * * 0' || github.event.inputs.day_to_test == 'Sunday'
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python sunday.py

      - name: Run Monday Script
        if: github.event.schedule == '0 6 * * 1' || github.event.inputs.day_to_test == 'Monday'
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python monday.py
