name: Daily Fellowship Robot

on:
  schedule:
    # يعمل الساعة 06:00 صباحاً بتوقيت UTC كل يوم
    - cron: '7 6 * * *'
  workflow_dispatch: # يسمح لك بتشغيله يدوياً للاختبار

jobs:
  run-robot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Daily Robot
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: python robot.py
